import type { Slide } from "../types";

export const idorSlides: Slide[] = [
  {
    kicker: "Scenario 01 · Panoramica",
    title: "Vulnerabilità IDOR",
    body: "In un'app web tutto ha un numero: l'ordine 1042, il profilo 42, il documento 87. L'IDOR nasce quando l'app ti fa cambiare quel numero nella URL e non controlla se quel numero ti appartiene davvero. Così puoi leggere cose di altre persone.",
    note: "È una delle vulnerabilità più diffuse al mondo, e anche una delle più facili da capire: nessun attacco avanzato, solo un numero cambiato nella URL.",
    bullets: ["Nessuno strumento richiesto", "Cambiare un numero basta", "Lo troverai in quasi ogni app web"],
    accent: "gold",
    icon: "ShieldAlert",
  },
  {
    kicker: "Task 01 · Osserva",
    title: "Tutto ha un numero: trovalo",
    body: "Il primo esercizio è allenare l'occhio. Guarda la barra degli URL, i form, i cookie: da qualche parte l'app mostra sempre il numero dell'oggetto che stai vedendo. Trovarlo è sempre il primo passo, prima di provare qualsiasi cosa.",
    note: "Nessun attacco qui: guardiamo solo dove l'app mostra i suoi oggetti. Esempio: /ordini/1042 → il numero è 1042.",
    bullets: [
      "Dove cercare: URL, form, cookie, chiamate API",
      "Esempio: /ordini/1042 → il numero è 1042",
      "Annotalo: ti servirà nei task successivi",
    ],
    icon: "Eye",
  },
  {
    kicker: "Task 02 · Il primo IDOR",
    title: "Cambia il numero, leggi un ordine di un altro",
    body: "Sei loggato e la pagina mostra il tuo ordine, il 1042. Adesso prova a scrivere 1043 al posto di 1042 nella URL: se il server non controlla chi è il proprietario, ti mostra un ordine che non è tuo.",
    note: "Il difetto è doppio: l'app si fida del numero che le mandi, e il server non si chiede «questo ordine appartiene davvero a chi lo sta chiedendo?».",
    accent: "danger",
    icon: "MousePointerClick",
  },
  {
    kicker: "Task 03 · Enumeration",
    title: "Da un numero a mille",
    body: "Un attaccante non prova un numero solo: passa in rassegna centinaia di numeri uno dopo l'altro, e in pochi minuti legge interi database. Numeri vicini tra loro (1042, 1043, 1044…) sono il bersaglio perfetto: ogni numero esiste ed è di qualcuno.",
    note: "Rischio GDPR reale: dati personali esposti in massa — fatture, contratti, buste paga scaricabili in serie. La conseguenza è legale, non solo tecnica.",
    bullets: [
      "Numeri vicini = facile passarli tutti in rassegna",
      "Fatture, contratti, buste paga: tutto leggibile",
      "Conseguenza legale, non solo tecnica",
    ],
    accent: "danger",
    icon: "Layers",
  },
  {
    kicker: "Task 04 · Privilege escalation",
    title: "Il numero 1 è quasi sempre l'admin",
    body: "In quasi ogni app il primo utente creato è l'amministratore. E se i numeri partono da 1, aprire /profile/1 significa cercare di entrare nel pannello di controllo di sistema senza password.",
    note: "IDOR + numeri facili da indovinare = puoi passare da cliente normale ad admin senza credenziali. Nel task caricherai un profilo «sbagliato» e vedrai cosa c'è dietro.",
    accent: "danger",
    icon: "Crown",
  },
  {
    kicker: "Task 05-06 · Dove si nasconde",
    title: "Non solo URL: anche nei form",
    body: "L'IDOR può stare anche in un campo nascosto di un form, in un messaggio inviato a un'API, in un header HTTP. La regola è una: tutto quello che parte dal tuo browser si può cambiare in pochi secondi con DevTools.",
    bullets: [
      "/download?doc=87 → cambia il numero e scarichi il documento di un altro",
      "I campi nascosti si vedono con DevTools",
      "«Mai fidarsi del client»: il client è sempre gestito dall'attaccante",
    ],
    icon: "Boxes",
  },
  {
    kicker: "Task 07 · UUID",
    title: "Anche i numeri lunghi possono ingannare",
    body: "Un UUID sembra una difesa perfetta: 32 caratteri esadecimali, trilioni di combinazioni. Ma non è magico: se generato male resta indovinabile, e la lunghezza dà solo un falso senso di sicurezza.",
    note: "La difesa vera è la casualità crittografica: crypto.randomUUID() nel browser, gen_random_uuid() in PostgreSQL. E comunque resta una difesa in più, non un sostituto del controllo lato server.",
    bullets: [
      "crypto.randomUUID(): generazione sicura",
      "gen_random_uuid() in PostgreSQL",
      "Una difesa in più, mai un sostituto",
    ],
    icon: "Fingerprint",
  },
  {
    kicker: "Task 08 · API REST",
    title: "Stesso attacco, ancora più veloce",
    body: "Le API mostrano le cose direttamente: GET /api/users/42 restituisce il profilo 42 come JSON. Non c'è una pagina che filtra o rallenta: cambi il numero e subito arriva il risultato.",
    note: "Il pattern non cambia — cambi solo il numero — ma l'impatto è più grande: le API sono fatte per essere chiamate in serie, esattamente ciò che serve all'attacco.",
    accent: "danger",
    icon: "Network",
  },
  {
    kicker: "Task 09 · Client bypass",
    title: "Il browser non è una difesa",
    body: "Un bottone «disabled» blocca solo il click nel tuo browser. Lo togli con DevTools in due secondi e l'azione parte lo stesso, se il server non ricontrolla. Nel task fisserai questo principio in pratica.",
    note: "Nascondere all'utente normale non equivale a difendersi: un attaccante vede tutto ciò che l'app manda e può eseguire qualunque azione, non solo quelle mostrate dall'interfaccia.",
    icon: "Unlock",
  },
  {
    kicker: "Task 10 · Sintesi",
    title: "Le tre regole d'oro",
    body: "Dieci domande finali per fissare i concetti, poi si passa alla pratica. Se le rispondi tutte, hai capito l'IDOR: ricapitola con le tre regole che vorresti vedere in ogni app che usi.",
    note: "Consiglio: rispondi prima senza rileggere le slide. Le domande non sono difficili, servono solo a capire se i concetti sono entrati.",
    bullets: [
      "1 · Controlli sempre lato server, a ogni richiesta",
      "2 · Numeri non facili da indovinare (UUID casuali, chiavi opache)",
      "3 · Mai fidarsi del client: form, header, JS, tutto si può cambiare",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
