import type { Slide } from "../types";

export const reverseShellSlides: Slide[] = [
  {
    kicker: "Scenario 03 · Panoramica",
    title: "Reverse Shell su IIS",
    body: "Immagina un server Windows con un sito web. Se riusciamo a far eseguire sul server una pagina speciale, quella pagina può «chiamare» il nostro computer e aprirci una finestra di comandi. In questo scenario vediamo come un semplice upload dimenticato può portare fino a lì, passo dopo passo.",
    note: "Tutto è simulato nel browser: nessun vero server, nessun vero attacco. Ma i comandi, le porte e gli errori sono quelli che vedresti nel mondo reale.",
    bullets: [
      "Un upload mal configurato è spesso la porta d'ingresso",
      "Il server si collega a te: ecco il «reverse» di reverse shell",
      "Da una pagina web a una shell di comandi sul server",
    ],
    accent: "gold",
    icon: "Server",
  },
  {
    kicker: "Task 01 · Ricognizione",
    title: "Prima di tutto: guarda con cosa hai a che fare",
    body: "Prima di qualsiasi cosa, diamo un'occhiata al target. Con uno strumento di scansione scopriamo che il computer 10.10.24.17 ha il sito web IIS, cioè il web server di Windows. Questo cambia tutto: i file del sito si chiamano .aspx e i comandi si danno con PowerShell.",
    note: "Esempio del comando reale: nmap -sV 10.10.24.17 → scopre che gira Microsoft-IIS/10.0 su Windows Server 2019. Non attaccare alla cieca: prima guarda, poi agisci.",
    bullets: [
      "nmap -sV: scopre porte, servizi e versioni",
      "Microsoft-IIS/10.0 = web server Microsoft su Windows",
      "Da qui in poi usiamo file .aspx e PowerShell",
    ],
    icon: "ScanLine",
  },
  {
    kicker: "Task 02 · Mappa del sito",
    title: "Trovare dove si carica un file",
    body: "Per attaccare un sito con una webshell servono tre cose insieme. Prima: da qualche parte puoi caricare un tuo file. Seconda: dopo il caricamento, quel file si apre con un normale indirizzo web (come https://sito.it/uploads/shell.aspx). Terza: il server esegue i file di quella cartella invece di mostrarli come testo. Se manca anche una sola di queste tre cose, l'attacco non funziona. Nel task navighiamo il sito e proviamo gli indirizzi /upload e /uploads/ per trovare dove sono.",
    note: "Ricordala come una catena di tre anelli: carica → serve → esegue. Se uno dei tre anelli si spezza, tutto si ferma. Per questo il difensore deve toglierne anche uno solo: ad esempio salvando i file caricati dove non vengono eseguiti.",
    bullets: [
      "1. Carica — trovi una pagina che accetta i tuoi file (es. /upload)",
      "2. Serve — il file caricato è raggiungibile via web (es. /uploads/shell.aspx)",
      "3. Esegue — il server esegue quel file invece di mostrarlo come testo",
    ],
    icon: "Map",
  },
  {
    kicker: "Task 03 · Anatomia",
    title: "Com'è fatta una webshell ASPX",
    body: "Una webshell è una pagina web con un semplice trucco dentro: riceve un comando scritto nella URL, lo fa eseguire da Windows e ti mostra il risultato nella pagina. In pratica, comandi i server scrivendoli nella barra degli indirizzi, come se compilassi un modulo. In questo task ne leggiamo una minimalista, di poche righe, per capire come funziona.",
    note: "Il punto chiave: IIS esegue qualunque file .aspx gli arrivi, senza guardarne il contenuto. Quindi basta una pagina che inizia con la riga <%@ Page Language=\"C#\" %> perché Windows esegua i comandi che gli mandi. Ecco perché bastano poche righe.",
    bullets: [
      "Riceve il comando: arriva nella URL, dopo ?cmd (es. ?cmd=whoami)",
      "Lo esegue: la pagina lo passa a Windows, che lo esegue davvero",
      "Mostra il risultato: l'output del comando appare nella pagina, come risposta a un form",
    ],
    accent: "danger",
    icon: "FileCode",
  },
  {
    kicker: "Task 04 · Webshell in azione",
    title: "Carica la webshell, esegui comandi",
    body: "Ora mettiamo in pratica tutto. Passo 1: carichiamo il file cmd.aspx nel punto di upload del sito. Il server dovrebbe bloccare i file .aspx (perché sono pericolosi), ma oggi accetta qualunque cosa: è un errore grave. Passo 2: apriamo cmd.aspx nel browser, scrivendo il suo indirizzo. Passo 3: gli mandiamo un comando e lui lo esegue sul server al posto nostro.",
    note: "Con il comando whoami il server risponde: iis apppool\\defaultapppool. Significa che non siamo Administrator, ma un utente limitato. Non basta per controllare tutto il server — ecco perché dopo useremo una vera shell interattiva.",
    bullets: [
      "Chi siamo? → whoami. Come si chiama il server? → hostname",
      "Che indirizzo ha? → ipconfig. Cosa c'è in questa cartella? → dir",
      "Il difetto: l'upload accetta file .aspx senza controllare nulla",
    ],
    accent: "danger",
    icon: "Terminal",
  },
  {
    kicker: "Task 05 · Listener",
    title: "Preparare la porta a cui il server si collegherà",
    body: "Ricordi? Nella reverse shell è il server a chiamare te. Ti serve quindi una «orecchia» sul tuo computer che aspetti la chiamata: si chiama listener. Lo strumento standard si chiama netcat (nc): nel task lo avvii con nc -lvnp 4444 e vedi la porta 4444 in ascolto.",
    note: "Sotto la porta 1024 servono privilegi alti, quindi nei CTF si usa spesso 4444 o 9001. Nel mondo reale le porte «più credibili» sono quelle che i firewall lasciano aperte in uscita: 443, 8443, 53.",
    bullets: [
      "nc -lvnp <porta> = listener standard",
      "Nel CTF: 4444 o 9001 per convenzione",
      "Porte più credibili nel mondo reale: 443, 8443, 53",
    ],
    icon: "Radio",
  },
  {
    kicker: "Task 06 · Payload",
    title: "Costruire shell.aspx con LHOST e LPORT",
    body: "Ora componiamo il payload: una pagina .aspx che quando IIS la esegue avvia PowerShell e apre la connessione verso il tuo computer. Servono solo due cose: LHOST, cioè l'indirizzo del tuo computer, e LPORT, cioè la porta 4444 su cui stai ascoltando.",
    note: "La regola: LPORT deve coincidere esattamente con la porta del listener. Sbagliare LHOST o LPORT significa nessuna connessione, nessuna shell — ed è esattamente il tipo di errore che vedrai fare nel task se sbagli.",
    bullets: [
      "LHOST = indirizzo del tuo computer · LPORT = porta del listener",
      "Pagina .aspx + one-liner PowerShell = payload completo",
      "Sbagliare uno dei due parametri = nessuna shell",
    ],
    accent: "danger",
    icon: "Socket",
  },
  {
    kicker: "Task 07 · Il momento chiave",
    title: "Carica shell.aspx e trigga l'URL",
    body: "Il momento chiave. Carichi shell.aspx nel punto di upload, poi apri il suo indirizzo web. IIS la esegue, PowerShell parte e chiama il tuo computer: nel terminale vedi la connessione entrare da sola e compare la shell della vittima.",
    note: "La sequenza esatta: carichi il file → IIS lo salva in /uploads/shell.aspx → apri l'URL → IIS avvia powershell.exe → powershell chiama LHOST sulla porta LPORT → il tuo nc mostra «connect from …» e ti trovi davanti al prompt PS della vittima.",
    bullets: [
      "Prima Carica, poi Trigger",
      "Guarda il terminale: la connessione entra da sola",
      "Difesa più economica: non far eseguire gli .aspx caricati",
    ],
    accent: "danger",
    icon: "Zap",
  },
  {
    kicker: "Task 08 · Post-exploitation",
    title: "Dentro il server: guardarsi intorno",
    body: "Ora hai una finestra di comandi dentro il server. Cosa ci si fa? Si guarda intorno: chi sono (whoami), che file importanti conosce il server (web.config, appsettings.json), che password ci sono nelle impostazioni. Le password nei file di configurazione sono spesso il vero premio.",
    note: "Ecco perché una delle difese migliori è semplice: non tenere password nei file che il sito può leggere. La finestra di comandi di per sé fa poco — i danni veri vengono da quello che il server sa.",
    bullets: [
      "Chi sei: whoami · hostname",
      "Cosa conosce il server: web.config, appsettings.json",
      "Le password nei file di configurazione sono il vero premio",
    ],
    icon: "Search",
  },
  {
    kicker: "Task 09-10 · Difese e sintesi",
    title: "Cosa funziona davvero: difese e quiz",
    body: "Ragioniamo al contrario: dato l'attacco appena provato, quali chiusure avrebbero fermato la catena? Nel task 9 scegli tu le difese vere, scartando quelle solo apparenti; nel task 10 il quiz di 10 domande riassume tutto lo scenario.",
    note: "Le difese che funzionano: chiudere il triangolo dell'upload, non far eseguire i file caricati, dare privilegi minimi al sito e impedire al server di collegarsi fuori. Se sbagli il quiz, torna al task corrispondente — non c'è penalità nel riprovare.",
    bullets: [
      "1 · Non far eseguire gli .aspx caricati (accessPolicy=\"Read\")",
      "2 · Application pool con privilegi minimi",
      "3 · Impedire al server di collegarsi fuori (egress filtering)",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
