import type { Slide } from "../types";

export const reverseShellSlides: Slide[] = [
  {
    kicker: "Scenario 03 · Panoramica",
    title: "Reverse Shell su IIS",
    body: "Immagina un server Windows con un sito web. Se riusciamo a far eseguire sul server una pagina speciale, quella pagina può «chiamare» il nostro computer e aprirci una finestra di comandi. In questo scenario vediamo come un semplice upload dimenticato può portare fino a lì, passo dopo passo.",
    note: "Tutto è simulato nel browser: nessun vero server, nessun vero attacco. Ma i comandi, le porte e gli errori sono quelli che vedresti nel mondo reale.",
    bullets: [
      "Un upload mal configurato è spesso la porta d'ingresso",
      "Il server si collega a te: ecco il «reverse» di reverse shell",
      "Da una pagina web a una shell di comandi sul server",
    ],
    accent: "gold",
    icon: "Server",
  },
  {
    kicker: "Task 01 · Ricognizione",
    title: "Prima di tutto: guarda con cosa hai a che fare",
    body: "Prima di qualsiasi cosa, diamo un'occhiata al target. Con uno strumento di scansione scopriamo che il computer 10.10.24.17 ha il sito web IIS, cioè il web server di Windows. Questo cambia tutto: i file del sito si chiamano .aspx e i comandi si danno con PowerShell.",
    note: "Esempio del comando reale: nmap -sV 10.10.24.17 → scopre che gira Microsoft-IIS/10.0 su Windows Server 2019. Non attaccare alla cieca: prima guarda, poi agisci.",
    bullets: [
      "nmap -sV: scopre porte, servizi e versioni",
      "Microsoft-IIS/10.0 = web server Microsoft su Windows",
      "Da qui in poi usiamo file .aspx e PowerShell",
    ],
    icon: "ScanLine",
  },
  {
    kicker: "Task 02 · Mappa del sito",
    title: "Trovare dove si carica un file",
    body: "Per attaccare un sito con una webshell servono tre cose insieme. Prima: da qualche parte puoi caricare un tuo file. Seconda: dopo il caricamento, quel file si apre con un normale indirizzo web (come https://sito.it/uploads/shell.aspx). Terza: il server esegue i file di quella cartella invece di mostrarli come testo. Se manca anche una sola di queste tre cose, l'attacco non funziona. Nel task navighiamo il sito e proviamo gli indirizzi /upload e /uploads/ per trovare dove sono.",
    note: "Ricordala come una catena di tre anelli: carica → serve → esegue. Se uno dei tre anelli si spezza, tutto si ferma. Per questo il difensore deve toglierne anche uno solo: ad esempio salvando i file caricati dove non vengono eseguiti.",
    bullets: [
      "1. Carica — trovi una pagina che accetta i tuoi file (es. /upload)",
      "2. Serve — il file caricato è raggiungibile via web (es. /uploads/shell.aspx)",
      "3. Esegue — il server esegue quel file invece di mostrarlo come testo",
    ],
    icon: "Map",
  },
  {
    kicker: "Task 03 · Anatomia",
    title: "Com'è fatta una webshell ASPX",
    body: "Una webshell è una pagina web con un semplice trucco dentro: riceve un comando scritto nella URL, lo fa eseguire da Windows e ti mostra il risultato nella pagina. In pratica, comandi i server scrivendoli nella barra degli indirizzi, come se compilassi un modulo. In questo task ne leggiamo una minimalista, di poche righe, per capire come funziona.",
    note: "Il punto chiave: IIS esegue qualunque file .aspx gli arrivi, senza guardarne il contenuto. Quindi basta una pagina che inizia con la riga <%@ Page Language=\"C#\" %> perché Windows esegua i comandi che gli mandi. Ecco perché bastano poche righe.",
    bullets: [
      "Riceve il comando: arriva nella URL, dopo ?cmd (es. ?cmd=whoami)",
      "Lo esegue: la pagina lo passa a Windows, che lo esegue davvero",
      "Mostra il risultato: l'output del comando appare nella pagina, come risposta a un form",
    ],
    accent: "danger",
    icon: "FileCode",
  },
  {
    kicker: "Task 04 · Webshell in azione",
    title: "Carica la webshell, esegui comandi",
    body: "Ora mettiamo in pratica tutto. Passo 1: carichiamo il file cmd.aspx nel punto di upload del sito. Il server dovrebbe bloccare i file .aspx (perché sono pericolosi), ma oggi accetta qualunque cosa: è un errore grave. Passo 2: apriamo cmd.aspx nel browser, scrivendo il suo indirizzo. Passo 3: gli mandiamo un comando e lui lo esegue sul server al posto nostro.",
    note: "Con il comando whoami il server risponde: iis apppool\\defaultapppool. Significa che non siamo Administrator, ma un utente limitato. Non basta per controllare tutto il server — ecco perché dopo useremo una vera shell interattiva.",
    bullets: [
      "Chi siamo? → whoami. Come si chiama il server? → hostname",
      "Che indirizzo ha? → ipconfig. Cosa c'è in questa cartella? → dir",
      "Il difetto: l'upload accetta file .aspx senza controllare nulla",
    ],
    accent: "danger",
    icon: "Terminal",
  },
  {
    kicker: "Task 05 · Listener",
    title: "Preparare la porta a cui il server si collegherà",
    body: "Ricordi? Nella reverse shell è il server a chiamare te, non tu a chiamare il server. Quindi prima di tutto ti serve qualcuno che ascolti sul tuo computer: un programma che resta in attesa e aspetta la chiamata. Si chiama listener. Lo strumento standard si chiama netcat, e il comando si lancia così: nc -lvnp 4444. Le quattro lettere significano: l = ascolta (listen), v = mostrami quello che succede (verbose), n = usa solo numeri, niente nomi, p = la porta su cui aspettare, cioè 4444.",
    note: "Sotto la porta 1024 servono privilegi alti, quindi nei CTF si usa spesso 4444 o 9001. Nel mondo reale le porte «più credibili» sono quelle che i firewall lasciano aperte in uscita: 443, 8443, 53.",
    bullets: [
      "Listener = il tuo computer aspetta la chiamata del server",
      "nc -lvnp 4444 → l = listen, v = verbose, n = numerico, p = porta 4444",
      "Nel CTF: 4444 o 9001 · Nel mondo reale: 443, 8443, 53",
    ],
    icon: "Radio",
  },
  {
    kicker: "Task 06 · Payload",
    title: "Costruire shell.aspx con LHOST e LPORT",
    body: "Adesso costruiamo il payload: è il file che fa partire la reverse shell. In pratica è una pagina .aspx che contiene un comando PowerShell dentro. Quando IIS la esegue, quel comando parte e fa una cosa precisa: chiama il tuo computer sulla porta 4444, dove il tuo listener sta aspettando. Per funzionare gli servono solo due informazioni. LHOST: l'indirizzo del tuo computer (quello attaccato alla stessa rete del server, per esempio 10.10.14.5). LPORT: la porta su cui il tuo listener aspetta, cioè la 4444 che hai aperto nel task precedente.",
    note: "Regola d'oro: LPORT deve essere identico alla porta del listener. Se scrivi 4444 nel listener ma 5555 nel payload, il server chiama una porta dove nessuno ascolta: la chiamata cade nel vuoto e non arriva nessuna shell. Nel task vedrai esattamente questo errore, così impari a riconoscerlo.",
    bullets: [
      "Payload = pagina .aspx con dentro un comando PowerShell",
      "LHOST = l'indirizzo del tuo computer · LPORT = la porta del listener (4444)",
      "Se LHOST o LPORT sono sbagliati, il server chiama nel vuoto: nessuna shell",
    ],
    accent: "danger",
    icon: "Socket",
  },
  {
    kicker: "Task 07 · Il momento chiave",
    title: "Carica shell.aspx e apri il suo URL",
    body: "È il momento che tutto lo scenario prepara, e avviene in due passi. Primo passo: carichi il file shell.aspx nel punto di upload del sito, come se caricassi una foto. Secondo passo: apri nel browser l'indirizzo del file caricato, per esempio www.sito.com/uploads/shell.aspx. A quel punto succede qualcosa di importante: IIS vede un file .aspx e lo esegue, invece di mostrartelo. Dentro il file c'è il comando PowerShell del task precedente, quindi parte e chiama il tuo computer, che sta aspettando sulla porta 4444. Nel tuo terminale compare la scritta «connect from …»: la connessione è arrivata da sola, e ora hai davanti il prompt PS della vittima.",
    note: "Perché tutto funziona? Perché IIS esegue i file .aspx senza guardare cosa contengono. La difesa più economica nasce proprio da qui: se i file caricati non si eseguono mai (accessPolicy=\"Read\"), anche la webshell più perfetta resta un file morto.",
    bullets: [
      "Passo 1 · Carica shell.aspx nell'upload",
      "Passo 2 · Apri l'URL del file: IIS lo esegue",
      "Risultato · «connect from …» nel terminale: hai la shell",
    ],
    accent: "danger",
    icon: "Zap",
  },
  {
    kicker: "Task 08 · Post-exploitation",
    title: "Dentro il server: guardarsi intorno",
    body: "Ora hai una finestra di comandi dentro il server. Cosa ci si fa? Si guarda intorno: chi sono (whoami), che file importanti conosce il server (web.config, appsettings.json), che password ci sono nelle impostazioni. Le password nei file di configurazione sono spesso il vero premio.",
    note: "Ecco perché una delle difese migliori è semplice: non tenere password nei file che il sito può leggere. La finestra di comandi di per sé fa poco — i danni veri vengono da quello che il server sa.",
    bullets: [
      "Chi sei: whoami · hostname",
      "Cosa conosce il server: web.config, appsettings.json",
      "Le password nei file di configurazione sono il vero premio",
    ],
    icon: "Search",
  },
  {
    kicker: "Task 09-10 · Difese e sintesi",
    title: "Cosa funziona davvero: difese e quiz",
    body: "Ora ragioniamo al contrario: l'attacco ha funzionato, ma bastava una sola chiusura per fermarlo. Nel task 9 vedrai un elenco di difese e dovrai scegliere solo quelle vere, scartando quelle che sembrano funzionare ma non bloccano nulla. Nel task 10 un quiz di 10 domande ripassa tutto lo scenario.",
    note: "Ripassiamo le quattro difese vere: i file caricati non devono poter partire (non eseguibili), il sito gira con pochi privilegi, il server non può collegarsi a internet a sua scelta e la cartella di upload è isolata. Se sbagli una domanda del quiz, puoi riprovare senza problemi.",
    bullets: [
      "1 · I file caricati non devono partire: in IIS si imposta accessPolicy=\"Read\" così gli .aspx vengono solo letti, mai eseguiti",
      "2 · Pochi privilegi al sito: anche se un attaccante entra, l'utente IIS può fare pochissime cose",
      "3 · Il server non chiama fuori: bloccando le connessioni in uscita, la reverse shell non riesce a raggiungere l'attaccante",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
