import type { Slide } from "../types";

export const reverseShellSlides: Slide[] = [
  {
    kicker: "Scenario 03 · Panoramica",
    title: "Reverse Shell su IIS",
    body: "Immagina un server Windows con un sito web. Se riusciamo a far eseguire sul server una pagina speciale, quella pagina può «chiamare» il nostro computer e aprirci una finestra di comandi. In questo scenario vediamo come un semplice upload dimenticato può portare fino a lì, passo dopo passo.",
    note: "Tutto è simulato nel browser: nessun vero server, nessun vero attacco. Ma i comandi, le porte e gli errori sono quelli che vedresti nel mondo reale.",
    bullets: [
      "Un upload mal configurato è spesso la porta d'ingresso",
      "Il server si collega a te: ecco il «reverse» di reverse shell",
      "Da una pagina web a una shell di comandi sul server",
    ],
    accent: "gold",
    icon: "Server",
  },
  {
    kicker: "Task 01 · Ricognizione",
    title: "Prima di tutto: guarda con cosa hai a che fare",
    body: "Prima di qualsiasi cosa, diamo un'occhiata al target. Con uno strumento di scansione scopriamo che il computer 10.10.24.17 ha il sito web IIS, cioè il web server di Windows. Questo cambia tutto: i file del sito si chiamano .aspx e i comandi si danno con PowerShell.",
    note: "Esempio del comando reale: nmap -sV 10.10.24.17 → scopre che gira Microsoft-IIS/10.0 su Windows Server 2019. Non attaccare alla cieca: prima guarda, poi agisci.",
    bullets: [
      "nmap -sV: scopre porte, servizi e versioni",
      "Microsoft-IIS/10.0 = web server Microsoft su Windows",
      "Da qui in poi usiamo file .aspx e PowerShell",
    ],
    icon: "ScanLine",
  },
  {
    kicker: "Task 02 · Mappa del sito",
    title: "Trovare dove si carica un file",
    body: "Un sito diventa pericoloso quando tre elementi sono presenti: un punto dove puoi caricare un file, una cartella dove quel file si apre con un indirizzo web, e il fatto che in quella cartella i file si eseguono. Nel task navighiamo il sito e proviamo gli indirizzi /upload e /uploads/ per trovarli.",
    note: "Il triangolo da rompere: carica · serve · esegue. Basta chiudere uno dei tre lati per fermare tutto. Se /upload accetta file e /uploads/ li mostra a tutti, il cerchio è chiuso.",
    bullets: [
      "Tre lati del triangolo: carica · serve · esegue",
      "Prova /upload e /uploads/",
      "Gli header HTTP rivelano spesso molto",
    ],
    icon: "Map",
  },
  {
    kicker: "Task 03 · Anatomia",
    title: "Com'è fatta una webshell ASPX",
    body: "Una webshell è una pagina che riceve un comando, lo passa a Windows e mostra il risultato. È il «telecomando» dell'attaccante. In questo task ne leggiamo una semplicissima, fatta in poche righe, per capire come funziona.",
    note: "Il punto chiave: se IIS vede un file .aspx, lo esegue. Basta una pagina con la direttiva <%@ Page Language=\"C#\" %> perché il telecomando funzioni. Ecco perché le poche righe bastano.",
    bullets: [
      "Riceve ?cmd + passa il comando a Windows + mostra l'output",
      "Poche righe di C# = telecomando completo",
      "Ora la leggiamo; nel task 6 la trasformeremo in reverse shell",
    ],
    accent: "danger",
    icon: "FileCode",
  },
  {
    kicker: "Task 04 · Webshell in azione",
    title: "Carica la webshell, esegui comandi",
    body: "Mettiamo in pratica: carichiamo cmd.aspx nel punto di upload — che oggi accetta qualunque tipo di file, anche i .aspx: grande difetto! — poi la apriamo nel browser e proviamo whoami (chi sono?), ipconfig (che indirizzo ha il server?) e dir (cosa c'è in questa cartella?).",
    note: "Guarda la risposta di whoami: iis apppool\\defaultapppool. Non sei Administrator: sei un utente limitato. Puoi già leggere i file del sito, ma il vero salto sarà avere una shell interattiva.",
    bullets: [
      "Comandi utili: whoami, hostname, ipconfig, dir",
      "L'upload accetta qualunque estensione: difetto elementare",
      "Ogni comando finisce nei log: attacco rumoroso ma efficace",
    ],
    accent: "danger",
    icon: "Terminal",
  },
  {
    kicker: "Task 05 · Listener",
    title: "Preparare la porta a cui il server si collegherà",
    body: "Ricordi? Nella reverse shell è il server a chiamare te. Ti serve quindi una «orecchia» sul tuo computer che aspetti la chiamata: si chiama listener. Lo strumento standard si chiama netcat (nc): nel task lo avvii con nc -lvnp 4444 e vedi la porta 4444 in ascolto.",
    note: "Sotto la porta 1024 servono privilegi alti, quindi nei CTF si usa spesso 4444 o 9001. Nel mondo reale le porte «più credibili» sono quelle che i firewall lasciano aperte in uscita: 443, 8443, 53.",
    bullets: [
      "nc -lvnp <porta> = listener standard",
      "Nel CTF: 4444 o 9001 per convenzione",
      "Porte più credibili nel mondo reale: 443, 8443, 53",
    ],
    icon: "Radio",
  },
  {
    kicker: "Task 06 · Payload",
    title: "Costruire shell.aspx con LHOST e LPORT",
    body: "Ora componiamo il payload: una pagina .aspx che quando IIS la esegue avvia PowerShell e apre la connessione verso il tuo computer. Servono solo due cose: LHOST, cioè l'indirizzo del tuo computer, e LPORT, cioè la porta 4444 su cui stai ascoltando.",
    note: "La regola: LPORT deve coincidere esattamente con la porta del listener. Sbagliare LHOST o LPORT significa nessuna connessione, nessuna shell — ed è esattamente il tipo di errore che vedrai fare nel task se sbagli.",
    bullets: [
      "LHOST = indirizzo del tuo computer · LPORT = porta del listener",
      "Pagina .aspx + one-liner PowerShell = payload completo",
      "Sbagliare uno dei due parametri = nessuna shell",
    ],
    accent: "danger",
    icon: "Socket",
  },
  {
    kicker: "Task 07 · Il momento chiave",
    title: "Carica shell.aspx e trigga l'URL",
    body: "Il momento chiave. Carichi shell.aspx nel punto di upload, poi apri il suo indirizzo web. IIS la esegue, PowerShell parte e chiama il tuo computer: nel terminale vedi la connessione entrare da sola e compare la shell della vittima.",
    note: "La sequenza esatta: carichi il file → IIS lo salva in /uploads/shell.aspx → apri l'URL → IIS avvia powershell.exe → powershell chiama LHOST sulla porta LPORT → il tuo nc mostra «connect from …» e ti trovi davanti al prompt PS della vittima.",
    bullets: [
      "Prima Carica, poi Trigger",
      "Guarda il terminale: la connessione entra da sola",
      "Difesa più economica: non far eseguire gli .aspx caricati",
    ],
    accent: "danger",
    icon: "Zap",
  },
  {
    kicker: "Task 08 · Post-exploitation",
    title: "Dentro il server: guardarsi intorno",
    body: "Ora hai una finestra di comandi dentro il server. Cosa ci si fa? Si guarda intorno: chi sono (whoami), che file importanti conosce il server (web.config, appsettings.json), che password ci sono nelle impostazioni. Le password nei file di configurazione sono spesso il vero premio.",
    note: "Ecco perché una delle difese migliori è semplice: non tenere password nei file che il sito può leggere. La finestra di comandi di per sé fa poco — i danni veri vengono da quello che il server sa.",
    bullets: [
      "Chi sei: whoami · hostname",
      "Cosa conosce il server: web.config, appsettings.json",
      "Le password nei file di configurazione sono il vero premio",
    ],
    icon: "Search",
  },
  {
    kicker: "Task 09-10 · Difese e sintesi",
    title: "Cosa funziona davvero: difese e quiz",
    body: "Ragioniamo al contrario: dato l'attacco appena provato, quali chiusure avrebbero fermato la catena? Nel task 9 scegli tu le difese vere, scartando quelle solo apparenti; nel task 10 il quiz di 10 domande riassume tutto lo scenario.",
    note: "Le difese che funzionano: chiudere il triangolo dell'upload, non far eseguire i file caricati, dare privilegi minimi al sito e impedire al server di collegarsi fuori. Se sbagli il quiz, torna al task corrispondente — non c'è penalità nel riprovare.",
    bullets: [
      "1 · Non far eseguire gli .aspx caricati (accessPolicy=\"Read\")",
      "2 · Application pool con privilegi minimi",
      "3 · Impedire al server di collegarsi fuori (egress filtering)",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
