import type { Slide } from "../types";

export const traversalSlides: Slide[] = [
  {
    kicker: "Scenario 02 · Panoramica",
    title: "Directory Traversal",
    body: "Quando un'app ti fa scaricare o leggere un file, il server prende il nome che gli mandi e apre il file. Se il nome contiene i simboli ../ puoi «uscire dalla cartella» e fargli aprire file che non dovrebbe: password, chiavi private, file di sistema.",
    note: "Nessun attacco complicato: è il sistema operativo stesso che interpreta ../ come «torna indietro di una cartella». Il difetto è che il server non verifica mai dove finisce il percorso.",
    bullets: [
      "Un input cambiato basta: file=../",
      "File di prova classici: /etc/passwd su Linux, win.ini su Windows",
      "Il vero obiettivo: file di configurazione con le password",
    ],
    accent: "gold",
    icon: "FolderOpen",
  },
  {
    kicker: "Task 01 · Osserva",
    title: "Come il server trova un file",
    body: "Un server ha sempre una cartella di partenza e ci aggiunge il nome che gli mandi: /var/www/html/pages + note.txt → /var/www/html/pages/note.txt. Nel primo esercizio aprirai due file legittimi e osserverai come si compone il percorso finale.",
    note: "Nessun attacco qui: capire questo meccanismo è essenziale, perché la vulnerabilità nasce esattamente quando l'input può cambiare la parte «cartella» del percorso, non solo il nome del file.",
    bullets: [
      "Esempio tipico: /read?file=note.txt",
      "Il server apre quel percorso e ti restituisce il contenuto",
      "Meccanismo diffusissimo: download di allegati, viewer di documenti",
    ],
    icon: "Eye",
  },
  {
    kicker: "Task 02 · Il primo traversal",
    title: "Tornare indietro con ../",
    body: "Nel filesystem ../ significa «torna indietro di una cartella»: è un meccanismo standard di ogni sistema operativo. Se mandi ../index.html, il server torna indietro di un livello e apre /var/www/html/index.html — sei uscito dalla cartella prevista.",
    note: "Il difetto è che il server non si chiede mai «il percorso finale resta davvero dentro la mia cartella?». È proprio questa verifica mancante il difetto più comune nei bug trovati in produzione.",
    accent: "danger",
    icon: "CornerLeftUp",
  },
  {
    kicker: "Task 03 · Uscire fino alla radice",
    title: "Leggere /etc/passwd",
    body: "Dalla cartella di partenza servono quattro ../ per arrivare in cima, poi puoi andare ovunque. Puoi anche metterne troppi: arrivare in cima e continuare non dà errore, il sistema si ferma semplicemente lì. /etc/passwd elenca gli utenti del sistema — è il file di prova classico.",
    note: "/etc/passwd non contiene password (quelle sono protette), ma è la prova che il server legge file arbitrari: nel pentest è la conferma che l'attacco funziona.",
    bullets: [
      "Payload: ?file=../../../../etc/passwd",
      "Ogni ../ risale di un livello; la cima ferma tutto",
      "Leggere file di sistema = prova che l'attacco funziona",
    ],
    accent: "danger",
    icon: "FileKey",
  },
  {
    kicker: "Task 04 · Windows/IIS",
    title: "Uscire dalla cartella anche su Windows",
    body: "Su Windows la logica è identica ma cambiano i dettagli: le cartelle si separano con \\, i percorsi partono da C:\\, e IIS serve i file da C:\\inetpub\\wwwroot. I file di prova diventano win.ini (l'equivalente storico di /etc/passwd) e la mappa di rete in hosts.",
    note: "L'attacco funziona su qualsiasi sistema operativo: cambia il principio di nulla, cambiano solo file di prova e separatori. È anche il contesto in cui vive lo scenario successivo del modulo Reverse Shell (che vedremo dopo).",
    bullets: [
      "File di prova tipico: C:\\Windows\\win.ini",
      "C:\\Windows\\System32\\drivers\\etc\\hosts",
      "Stesso attacco, dettagli diversi",
    ],
    icon: "HardDrive",
  },
  {
    kicker: "Task 05 · Primo bypass",
    title: "Codificare i caratteri: %2e%2e%2f",
    body: "Alcuni server si difendono così: «se nel nome del file c'è ../, blocco la richiesta». Sembra furbo, ma c'è un problema: nella URL i caratteri si possono scrivere in forma codificata. Il punto . diventa %2e e la barra / diventa %2f. Quindi ../ si può scrivere come %2e%2e%2f: per il filtro è una stringa innocua, ma quando il server la decodifica e apre il file, torna ad essere ../.",
    note: "Il filtro controlla la stringa prima di decodificarla, il sistema operativo la legge dopo. Regola generale: prima decodifica, poi controlla.",
    bullets: [
      "%2e = . e %2f = / → ../ diventa %2e%2e%2f",
      "Il filtro vede una stringa innocua, il file system riceve ../",
      "Difesa corretta: decodifica e normalizza PRIMA di controllare",
    ],
    accent: "danger",
    icon: "Repeat",
  },
  {
    kicker: "Task 06 · Due sistemi che decodificano",
    title: "Codificare due volte con %25",
    body: "A volte il filtro non sta da solo: la richiesta passa prima per altri sistemi (proxy, framework, application server), e qualcuno di questi decodifica i caratteri %2e e %2f. Il trucco qui è codificare due volte: ricordati che il simbolo % stesso si scrive %25. Quindi per ottenere . scrivi prima %2e, poi codifichi di nuovo il suo % e ottieni %252e. Al primo giro un sistema converte %25 in %, e la stringa diventa %2e. Al secondo giro il filtro la controlla... ma se il controllo avviene prima dell'ultima decodifica, il punto vero appare solo dopo.",
    note: "Morale: decodifica una volta sola, in un solo posto, e solo dopo controlla il percorso finale. Ogni sistema che decodifica in più è una nuova occasione per sbagliare.",
    bullets: [
      "%25 = % · quindi: . → %2e → %252e",
      "Primo giro: %252e → %2e · Secondo giro: %2e → .",
      "Il filtro vede una stringa pulita, il file system riceve i ../ veri",
      "Difesa: decodifica tutto, poi controlla dove finisce il percorso",
    ],
    accent: "danger",
    icon: "Shuffle",
  },
  {
    kicker: "Task 07 · Un sistema aggiunge, un altro taglia",
    title: "Il trucco storico del null byte",
    body: "Immagina un server che dice: «ti servo solo file .txt». Se chiedi il file report, il server aggiunge da solo .txt alla fine e apre report.txt. Come leggere allora un altro file, per esempio passwd? Si chiede passwd%00.txt. Quel %00 (scritto anche \\0) si chiama null byte: è un carattere invisibile che nel passato significava «la stringa finisce qui». I vecchi sistemi (PHP 5, ColdFusion, Perl) leggevano il nome solo fino a quel punto: il controllo vedeva «passwd%00.txt» (estensione ok) ma il file aperto era soltanto «passwd».",
    note: "Oggi i sistemi moderni bloccano il null byte, quindi questo trucco non funziona quasi più. Ma resta il pattern di fondo: due componenti leggono la stessa stringa in modo diverso — uno la taglia, l'altro la legge intera. Ogni volta che due parti non sono d'accordo, nasce una vulnerabilità.",
    bullets: [
      "Difesa del server: «all'input aggiungo io .txt alla fine»",
      "Trucco: passwd\0.txt — il null byte taglia via il .txt",
      "Il controllo vede .txt, il file aperto è passwd",
      "Oggi bloccato, ma il pattern «due letture diverse» torna sempre",
    ],
    icon: "Scissors",
  },
  {
    kicker: "Task 08-09 · Il vero obiettivo",
    title: "Rubare le password nei file di configurazione",
    body: "Un attaccante non si accontenta di /etc/passwd: il vero obiettivo sono app.conf, .env, database.yml, web.config — file che spesso contengono in chiaro utente e password del database, chiavi API, token cloud. E l'input non arriva solo dalla URL: anche un messaggio API con un campo filename può finire in una apertura di file.",
    note: "Con utente e password del database, l'attaccante entra direttamente senza passare per l'applicazione, saltando tutti i controlli. Difese: non mandare mai nomi di file dal client (usa un numero nel database, e il server trova da solo il percorso) e tenere le password fuori dai file — variabili d'ambiente o secret manager.",
    bullets: [
      "app.conf / .env / database.yml: password in chiaro",
      "Messaggi API, header, cookie: tutto input che si può cambiare",
      "Numeri opachi + secret manager = il difetto sparisce del tutto",
    ],
    accent: "danger",
    icon: "Vault",
  },
  {
    kicker: "Task 10 · Sintesi",
    title: "Le tre regole d'oro",
    body: "Dieci domande finali per fissare i concetti, poi si passa alla pratica. Le domande ripercorrono il modulo: cos'è l'uscita dalla cartella, come si aggirano i filtri, dove si nasconde oltre che negli URL, e le difese davvero efficaci. Se sbagli, torna al task corrispondente — non c'è penalità nel riprovare.",
    note: "Consiglio: rispondi prima senza rileggere le slide, poi chiediti: chi decodifica? dove sta il filtro? la password sta in un file o fuori?",
    bullets: [
      "1 · Decodifica e normalizza PRIMA di controllare",
      "2 · Chiudi il processo in un spazio protetto: container, permessi minimi",
      "3 · Mai mandare nomi di file dal client: usa un numero nel database",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
