import type { Slide } from "../types";

export const revengSlides: Slide[] = [
  {
    kicker: "Scenario 04 · Panoramica",
    title: "Reverse Engineering (base)",
    body: "Il reverse engineering significa capire cosa fa un programma leggendolo, senza mai eseguirlo. È quello che fa un meccanico quando smonta un motore per vedere com'è fatto dentro.\nIn questo scenario trovi sul computer di un utente un file chiamato update.ps1. Sembra un aggiornamento innocuo, ma non lo è. Lo smontiamo pezzo per pezzo: prima lo leggiamo, poi scopriamo cosa nasconde, infine scriviamo lo script che cancella i suoi effetti.",
    note: "Niente di strano o particolare: è metodo. I programmi malevoli fatti in fretta usano sempre gli stessi pochi trucchi per nascondersi. In questo modulo li vedremo tutti, uno alla volta.",
    bullets: [
      "Leggere un codice è il primo passo per difendersi",
      "Tre livelli di nascondiglio, ognuno più tosto del precedente",
      "L'AI può aiutarti: devi solo fargli le domande giuste",
    ],
    accent: "gold",
    icon: "Wrench",
  },
  {
    kicker: "Task 01 · Le basi",
    title: "Com'è fatto uno script PowerShell",
    body: "Prima di smontare qualcosa, bisogna saper leggere il linguaggio in cui è scritto. PowerShell è il linguaggio con cui si amministra Windows: se un attaccante vuole controllare un PC Windows, quasi sempre lo fa con PowerShell.\nLa buona notizia: le regole sono poche e semplici. Ogni comando ha la forma Verbo-Nome: Get-Date significa «prendi la data», Write-Host significa «scrivi sullo schermo». Le variabili iniziano tutte con il simbolo $, i commenti iniziano con # e servono solo a spiegare il codice a chi legge.",
    note: "Sono le tre cose che ti servono per leggere lo script sospetto del prossimo task. Nel task vedi uno script PowerShell più innocuo possibile: «ciao mondo con la data di oggi».",
    bullets: [
      "Comandi = Verbo-Nome: Get-Date, Write-Host",
      "Variabili = $nome (il $ dice «questa è una variabile»)",
      "Commenti = # riga di spiegazione, il computer la ignora",
    ],
    icon: "BookOpen",
  },
  {
    kicker: "Task 02 · Primo sguardo",
    title: "Lo script sospetto: cosa tradisce le cattive intenzioni",
    body: "Arriva lo script sospetto: update.ps1, che finge di essere un aggiornamento. La regola numero uno del reverse engineering è: non eseguirlo mai. Si legge, si guarda, si analizza — ma non si preme invio.\nCosa cerchiamo mentre lo leggiamo? Le parole che tradiscono le cattive intenzioni: codice nascosto, un download da un indirizzo strano, l'esecuzione nascosta e l'avvio automatico a ogni accensione del PC. Basta trovarne un paio insieme per capire che quello script non è un aggiornamento.",
    note: "Lo script mostra, solo per far vedere come funziona, una simulazione di avvio automatico nel registro di Windows (la chiave Run), un download in %TEMP%\\a.ps1 e la sua esecuzione. Tutto display-only: non viene mai eseguito davvero.",
    bullets: [
      "-EncodedCommand: codice nascosto in Base64",
      "Chiave Run del registro = si avvia a ogni accensione",
      "Download da IP sospetto + esecuzione = allarme",
    ],
    accent: "danger",
    icon: "AlertTriangle",
  },
  {
    kicker: "Task 03 · Primo nascondiglio",
    title: "Decodificare Base64",
    body: "Il primo tentativo di camuffamento si chiama -EncodedCommand. Invece di scrivere il comando in chiaro, l'attaccante lo trasforma in una fila di lettere senza senso: quella codifica si chiama Base64. Qui viene il bello: Base64 non è un segreto. Non è crittografia, è solo un modo diverso di scrivere la stessa cosa — come scrivere una parola al contrario. Chiunque può tornare indietro, e nel task lo facciamo davvero: decodifichiamo la stringa nel browser e leggiamo il comando che c'era dietro.",
    note: "Ecco come funziona in pratica: l'attaccante lancia powershell -EncodedCommand <base64>, cioè passa a PowerShell il comando camuffato. PowerShell lo decodifica da solo ed esegue il comando vero. A noi basta decodificare quella stringa per leggere il comando nascosto. Un solo dettaglio da sapere: la stringa usa il formato UTF-16LE, una variante di Base64 che occupa due byte per ogni carattere — non ti devi preoccupare di questo, il task lo gestisce automaticamente.",
    bullets: [
      "Base64 è una maschera, non un segreto: nasconde il testo a chi lo legge, ma chiunque può togliere la maschera e tornare al testo originale",
      "Il formato è UTF-16LE: una variante di Base64 in cui ogni carattere occupa due byte invece di uno",
      "In questo corso decodifichiamo solo per leggere: apriamo il comando nascosto, non lo eseguiamo mai",
    ],
    accent: "danger",
    icon: "FileKey",
  },
  {
    kicker: "Task 04-05 · Secondo nascondiglio",
    title: "Codice smontato e rimontato",
    body: "Il malware non si ferma a Base64: smonta le stringhe in pezzi e le rimonta all'ultimo momento, quando il programma gira. Chi legge il codice trova solo pezzi sparsi; il computer, invece, li ricompone da solo.\nSono due varianti dello stesso trucco. Nel task 4 troviamo un comando Invoke-Expression (che significa «esegui quello che leggi») nascosto nella concatenazione di stringhe spezzate. Nel task 5 decodifichiamo un array di numeri: ogni numero è il codice di una lettera, quindi 72 diventa H e 73 diventa I.",
    note: "Esempio: [char[]](72,73) → 'HI'. Il computer conosce la tavola dei caratteri e riconstruisce il messaggio. Tu fai la stessa cosa al contrario: parti dai numeri e risali alle lettere.",
    bullets: [
      "Concatenazione: stringhe spezzate e ricomposte al volo",
      "Char-code: ogni lettera diventa un numero",
      "Lo schema si ripete: ricostruisci → leggi → capisci",
    ],
    accent: "danger",
    icon: "Puzzle",
  },
  {
    kicker: "Task 06 · Terzo nascondiglio",
    title: "XOR: ogni lettera mescolata con un numero segreto",
    body: "Terzo e ultimo livello: XOR. È un'operazione matematica semplicissima che «mescola» ogni lettera del messaggio con un numero segreto, chiamato chiave. Il risultato sembra rumore casuale.\nMa XOR ha una proprietà che lo rende debole: è reversibile. Se applichi di nuovo la stessa chiave al testo mescolato, torna tutto in chiaro — la mescolanza si annulla. E siccome qui la chiave è un solo numero (da 1 a 255), le possibilità sono finite: basta provarle tutte. Nel task lo fai muovendo uno slider e guardando il testo apparire.",
    note: "XOR con una chiave singola è indecifrabile in teoria ma debole in pratica: prova tutti i 256 numeri possibili e uno è quello giusto — esattamente quello che farai con lo slider.",
    bullets: [
      "XOR è reversibile: stesso numero per nascondere e mostrare",
      "Chiave a 1 numero = 256 possibilità, tutte provabili",
      "Lo slider ti fa vedere la chiave giusta in tempo reale",
    ],
    accent: "danger",
    icon: "KeyRound",
  },
  {
    kicker: "Task 07 · L'aiuto dell'AI",
    title: "Farsi aiutare dall'AI con le domande giuste",
    body: "Ora che conosci lo script, proviamo a farci aiutare dall'AI. L'AI legge il codice molto in fretta, ma la qualità della risposta dipende tutta dalla domanda che gli fai.\nUna domanda vaga («questo file è pericoloso?») porta a una risposta vaga. Una domanda precisa porta a un'analisi precisa: gli dici che tipo di file è, dove l'hai trovato, e cosa vuoi sapere — il comportamento passo per passo, gli indicatori di compromissione, e lo script che annulla i danni.",
    note: "Regola d'oro: non chiedere «dimmi se questo è pericoloso» — chiedi «spiega passo per passo cosa fa questo script, elenca gli indicatori di compromissione e scrivi lo script che annulla i suoi effetti».",
    bullets: [
      "Contesto: tipo di file, dove l'hai trovato",
      "Domande precise, risposta precisa",
      "Chiedi output strutturato: comportamento, indicatori, riparazione",
    ],
    icon: "Bot",
  },
  {
    kicker: "Task 08 · Verifica",
    title: "Capire cosa fa davvero lo script",
    body: "L'AI ti ha dato la sua analisi. Ma un'analisi automatica non va presa per buona: verificarla è il tuo lavoro. L'AI ti dà un punto di partenza, non una conclusione.\nNel task fai esattamente questo: classifichi tu il comportamento reale dello script, scegliendo le categorie giuste tra quelle proposte. Si avvia da solo al riavvio? Scarica file da internet? Li esegue? Se le tue risposte combaciano con quello che hai letto nei task precedenti, l'analisi è corretta.",
    note: "Mai fidarsi ciecamente di un'analisi automatica: è il punto di partenza, non la conclusione. La verifica umana è parte del lavoro.",
    accent: "danger",
    icon: "ClipboardCheck",
  },
  {
    kicker: "Task 09 · Controcolpo",
    title: "Scrivere lo script che «sistema tutto»",
    body: "Qui si chiude il cerchio: dal capire al riparare. Se sai esattamente cosa ha fatto il malware, sai anche esattamente cosa riparare.\nNel task scrivi lo script inverso: rimuove la chiave di avvio automatico dal registro, elimina i file scaricati e lascia il sistema pulito come prima. Ogni riga di pulizia corrisponde a un danno che abbiamo visto nei task precedenti — niente di inventato, niente di dimenticato.",
    note: "Esempio: se il malware ha scritto in HKCU:\\Software\\...\\Run\\OneDriveSync, la riparazione usa Remove-ItemProperty sulla stessa chiave e rimuove i file temporanei scaricati.",
    bullets: [
      "Ogni danno → una riga di pulizia",
      "Registro, file temporanei, processo: in quest'ordine",
      "Prova su ambiente isolato, mai sulla macchina reale",
    ],
    accent: "success",
    icon: "Undo2",
  },
  {
    kicker: "Task 10 · Sintesi",
    title: "Quiz finale: il metodo nel suo insieme",
    body: "Dieci domande per fissare l'intero metodo: leggere PowerShell, riconoscere i tre livelli di nascondiglio, usare bene l'AI e scrivere la riparazione. Le domande ripercorrono i task nell'ordine, quindi se ti blocchi su una sai già dove tornare a rileggere. Se sbagli, non succede nulla: si riprova senza problemi.",
    note: "Consiglio: rispondi prima senza rileggere le slide. Il reverse engineering è esattamente questo ciclo — osserva, decodifica, verifica, ripara — ripetuto ogni volta con un campione diverso.",
    bullets: [
      "1 · Leggi, non eseguire: il reverse parte sempre da qui",
      "2 · Nascondersi è un trucco prevedibile, e si può sempre annullare",
      "3 · L'AI accelera, ma la verifica resta tuo compito",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
